package com.certforge.audit;

public enum AuditEventType {
    GATEWAY_STARTED,
    GATEWAY_STOPPED,

    CONFIG_LOADED,
    CONFIG_NOT_FOUND,
    CONFIG_PARSE_ERROR,

    TOKEN_DISCOVERY_STARTED,
    TOKEN_DISCOVERY_COMPLETED,
    LIBRARY_PROBED,
    TOKEN_FOUND,

    AUTH_SUCCESS,
    AUTH_FAILED,

    SESSION_OPENED,
    SESSION_CLOSED,
    SESSION_EXPIRED,
    SESSION_NOT_FOUND,
    POOL_BORROW,
    POOL_RETURN,
    POOL_EXHAUSTED,
    POOL_EVICT,

    DOCUMENT_SIGNED,
    SIGNING_FAILED,

    DOCUMENT_VERIFIED,
    VERIFICATION_FAILED,

    ERROR,

    REQUEST_RECEIVED,
    REQUEST_COMPLETED
}